# Generated by Django 4.1.3 on 2022-12-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
