# Generated by Django 4.1.3 on 2022-12-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0002_bank_description_bank_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='ıban',
            field=models.IntegerField(null=True),
        ),
    ]
