# Generated by Django 4.1.3 on 2022-12-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_debt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
