# Generated by Django 4.1.3 on 2022-12-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('namesurname', models.CharField(max_length=20)),
                ('tc', models.IntegerField()),
                ('phoneNum', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('namesurname', models.CharField(max_length=20)),
                ('adet', models.IntegerField(default='')),
                ('daralı', models.IntegerField(default='')),
                ('safi', models.IntegerField(default='')),
                ('tutar', models.IntegerField(default='')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
