# Generated by Django 4.1.3 on 2022-12-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0004_customerstable_customerimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstable',
            name='customerImage',
            field=models.FileField(default='', null=True, upload_to='uploads'),
        ),
    ]
