# Generated by Django 4.1.3 on 2022-12-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0005_alter_customerstable_customerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstable',
            name='customerImage',
            field=models.ImageField(default='', null=True, upload_to='uploads'),
        ),
    ]
