# Generated by Django 4.1.3 on 2022-12-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0010_alter_price_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kilogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilo', models.FloatField()),
            ],
        ),
    ]
