# Generated by Django 4.1.3 on 2022-12-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0011_kilogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstable',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='producttable',
            name='date',
            field=models.DateField(),
        ),
    ]
