# Generated by Django 4.1.3 on 2022-12-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0012_alter_customerstable_date_alter_producttable_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttable',
            name='date',
        ),
    ]
