# Generated by Django 4.1.3 on 2022-12-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0013_remove_producttable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerstable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
