# Generated by Django 4.1.3 on 2022-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0018_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstable',
            name='phoneNum',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerstable',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='customerstable',
            name='tc',
            field=models.IntegerField(blank=True),
        ),
    ]
