# Generated by Django 4.1.3 on 2022-12-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0020_alter_customerstable_phonenum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesurname', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True)),
                ('adet', models.IntegerField(default='')),
                ('daralı', models.IntegerField(default='')),
                ('safi', models.IntegerField(default='')),
                ('tutar', models.IntegerField(default='')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
