# Generated by Django 4.1.3 on 2022-12-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0021_paids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paids',
            name='slug',
        ),
    ]
