# Generated by Django 4.1.3 on 2022-12-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aromaapp', '0023_paids_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paids',
            name='slug',
        ),
    ]
